name: Release Python Package

on:
  release:
    types: [published]
    paths:
      - 'pyproject.toml'

permissions:
  contents: read
  id-token: write

jobs:
  release-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  testpypi-publish:
    runs-on: ubuntu-24.04
    needs: release-build
    environment: testpypi
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: ${{ vars.TWINE_USER }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload --repository testpypi dist/* --verbose

  pypi-publish:
    runs-on: ubuntu-24.04
    needs: release-build
    environment: pypi
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ vars.TWINE_USER }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload --repository pypi dist/* --verbose